"""
Supabase client — compatibility wrapper for refactored module structure.

This module re-exports all functionality from the supabase package for backward
compatibility. New code should import directly from supabase submodules based on
domain (e.g., from supabase.workout_service import fetch_workouts).

The original monolithic supabase_client.py has been refactored into organized
domain services:
  - base.py: HTTP client setup and core REST utilities
  - user_service.py: User profiles and body measurements
  - workout_service.py: Workouts, routines, plans, exercises
  - meal_service.py: Meals, meal plans, food items
  - library_service.py: Exercise and food libraries
  - coach_service.py: Coach plans and muscles
  - social_service.py: Messages, follows, posts, comments
  - context_service.py: Bulk user data fetching for chatbot
"""

try:
    from .supabase import (
        get_http_client,
        close_http_client,
        headers,
        SUPABASE_URL,
        SUPABASE_KEY,
        SUPABASE_TIMEOUT,
        DEFAULT_LIMIT,
        LIBRARY_LIMIT,
        fetch_table,
        fetch_table_first,
        fetch_table_first_by_id,
        supabase_post,
        supabase_patch,
        supabase_delete,
        fetch_profile,
        fetch_user_profile,
        fetch_body_measurements,
        fetch_inbody,
        fetch_inbody_results,
        fetch_weight_logs,
        fetch_workouts,
        fetch_workout_sessions,
        fetch_workout_routines,
        fetch_workout_routine,
        fetch_workout_history,
        fetch_user_exercises,
        fetch_user_workout_sets,
        fetch_workout_plans,
        fetch_workout_plan_days,
        fetch_workout_plan_exercises,
        insert_workout_routine,
        update_workout_routine_by_id,
        insert_user_workout_session,
        update_user_workout_session_by_id,
        fetch_meals,
        fetch_meal_plans,
        fetch_meal_items,
        fetch_user_meal_checkins,
        fetch_food_items,
        fetch_food_item,
        fetch_exercise_library,
        fetch_coach_plan,
        fetch_plan_muscles,
        fetch_direct_messages,
        fetch_user_follows,
        fetch_user_posts,
        fetch_user_post_comments,
        fetch_user_post_likes,
        fetch_all_user_tables,
        build_user_context,
    )
except ImportError:
    from supabase import (
        get_http_client,
        close_http_client,
        headers,
        SUPABASE_URL,
        SUPABASE_KEY,
        SUPABASE_TIMEOUT,
        DEFAULT_LIMIT,
        LIBRARY_LIMIT,
        fetch_table,
        fetch_table_first,
        fetch_table_first_by_id,
        supabase_post,
        supabase_patch,
        supabase_delete,
        fetch_profile,
        fetch_user_profile,
        fetch_body_measurements,
        fetch_inbody,
        fetch_inbody_results,
        fetch_weight_logs,
        fetch_workouts,
        fetch_workout_sessions,
        fetch_workout_routines,
        fetch_workout_routine,
        fetch_workout_history,
        fetch_user_exercises,
        fetch_user_workout_sets,
        fetch_workout_plans,
        fetch_workout_plan_days,
        fetch_workout_plan_exercises,
        insert_workout_routine,
        update_workout_routine_by_id,
        insert_user_workout_session,
        update_user_workout_session_by_id,
        fetch_meals,
        fetch_meal_plans,
        fetch_meal_items,
        fetch_user_meal_checkins,
        fetch_food_items,
        fetch_food_item,
        fetch_exercise_library,
        fetch_coach_plan,
        fetch_plan_muscles,
        fetch_direct_messages,
        fetch_user_follows,
        fetch_user_posts,
        fetch_user_post_comments,
        fetch_user_post_likes,
        fetch_all_user_tables,
        build_user_context,
    )

__all__ = [
    "get_http_client",
    "close_http_client",
    "headers",
    "SUPABASE_URL",
    "SUPABASE_KEY",
    "SUPABASE_TIMEOUT",
    "DEFAULT_LIMIT",
    "LIBRARY_LIMIT",
    "fetch_table",
    "fetch_table_first",
    "fetch_table_first_by_id",
    "supabase_post",
    "supabase_patch",
    "supabase_delete",
    "fetch_profile",
    "fetch_user_profile",
    "fetch_body_measurements",
    "fetch_inbody",
    "fetch_inbody_results",
    "fetch_weight_logs",
    "fetch_workouts",
    "fetch_workout_sessions",
    "fetch_workout_routines",
    "fetch_workout_routine",
    "fetch_workout_history",
    "fetch_user_exercises",
    "fetch_user_workout_sets",
    "fetch_workout_plans",
    "fetch_workout_plan_days",
    "fetch_workout_plan_exercises",
    "insert_workout_routine",
    "update_workout_routine_by_id",
    "insert_user_workout_session",
    "update_user_workout_session_by_id",
    "fetch_meals",
    "fetch_meal_plans",
    "fetch_meal_items",
    "fetch_user_meal_checkins",
    "fetch_food_items",
    "fetch_food_item",
    "fetch_exercise_library",
    "fetch_coach_plan",
    "fetch_plan_muscles",
    "fetch_direct_messages",
    "fetch_user_follows",
    "fetch_user_posts",
    "fetch_user_post_comments",
    "fetch_user_post_likes",
    "fetch_all_user_tables",
    "build_user_context",
]
