"""
FitMentor — Exercise Database
Each exercise is a structured record with:
  - metadata (muscles, equipment, difficulty, type)
  - feature vector used for dot-product scoring
"""

import numpy as np

# ── Feature-vector index map ──────────────────────────────────────────────────
# [lose_weight, build_muscle, strength, endurance, maintain_weight,
#  beginner, intermediate, advanced,
#  compound, isolation,
#  chest, back, legs, shoulders, arms, core,
#  bodyweight, dumbbells, barbell, machines, cables, kettlebell]
FEATURE_LABELS = [
    "lose_weight", "build_muscle", "strength", "endurance", "maintain_weight",
    "beginner", "intermediate", "advanced",
    "compound", "isolation",
    "chest", "back", "legs", "shoulders", "arms", "core",
    "bodyweight", "dumbbells", "barbell", "machines", "cables", "kettlebell",
]
N_FEATURES = len(FEATURE_LABELS)


def _vec(**kwargs):
    v = np.zeros(N_FEATURES)
    for k, val in kwargs.items():
        v[FEATURE_LABELS.index(k)] = val
    return v


EXERCISES = [
    # ── CHEST ─────────────────────────────────────────────────────────────────
    {
        "name": "Barbell Bench Press",
        "muscles": ["chest"],
        "equipment": ["barbell"],
        "type": "compound",
        "difficulty": ["intermediate", "advanced"],
        "base_weight_pct": 0.70,          # % of user bodyweight as starting point
        "vector": _vec(build_muscle=1, strength=1, intermediate=1, advanced=1,
                       compound=1, chest=1, barbell=1),
    },
    {
        "name": "Dumbbell Bench Press",
        "muscles": ["chest"],
        "equipment": ["dumbbells"],
        "type": "compound",
        "difficulty": ["beginner", "intermediate"],
        "base_weight_pct": 0.30,
        "vector": _vec(lose_weight=0.5, build_muscle=1, beginner=1, intermediate=1,
                       compound=1, chest=1, dumbbells=1),
    },
    {
        "name": "Push-Up",
        "muscles": ["chest"],
        "equipment": ["bodyweight"],
        "type": "compound",
        "difficulty": ["beginner"],
        "base_weight_pct": 0.0,
        "vector": _vec(lose_weight=1, beginner=1, compound=1, chest=1, bodyweight=1),
    },
    {
        "name": "Cable Fly",
        "muscles": ["chest"],
        "equipment": ["cables"],
        "type": "isolation",
        "difficulty": ["intermediate"],
        "base_weight_pct": 0.15,
        "vector": _vec(lose_weight=0.5, build_muscle=1, intermediate=1,
                       isolation=1, chest=1, cables=1),
    },
    {
        "name": "Machine Chest Press",
        "muscles": ["chest"],
        "equipment": ["machines"],
        "type": "compound",
        "difficulty": ["beginner", "intermediate"],
        "base_weight_pct": 0.50,
        "vector": _vec(build_muscle=1, beginner=1, intermediate=1,
                       compound=1, chest=1, machines=1),
    },
    {
        "name": "Dumbbell Fly",
        "muscles": ["chest"],
        "equipment": ["dumbbells"],
        "type": "isolation",
        "difficulty": ["intermediate"],
        "base_weight_pct": 0.15,
        "vector": _vec(build_muscle=1, intermediate=1, isolation=1,
                       chest=1, dumbbells=1),
    },
    # ── BACK ──────────────────────────────────────────────────────────────────
    {
        "name": "Deadlift",
        "muscles": ["back"],
        "equipment": ["barbell"],
        "type": "compound",
        "difficulty": ["intermediate", "advanced"],
        "base_weight_pct": 1.00,
        "vector": _vec(strength=1, build_muscle=0.7, intermediate=1, advanced=1,
                       compound=1, back=1, barbell=1),
    },
    {
        "name": "Barbell Row",
        "muscles": ["back"],
        "equipment": ["barbell"],
        "type": "compound",
        "difficulty": ["intermediate", "advanced"],
        "base_weight_pct": 0.60,
        "vector": _vec(strength=1, build_muscle=1, intermediate=1, advanced=1,
                       compound=1, back=1, barbell=1),
    },
    {
        "name": "Dumbbell Row",
        "muscles": ["back"],
        "equipment": ["dumbbells"],
        "type": "compound",
        "difficulty": ["beginner", "intermediate"],
        "base_weight_pct": 0.25,
        "vector": _vec(build_muscle=1, beginner=1, intermediate=1,
                       compound=1, back=1, dumbbells=1),
    },
    {
        "name": "Lat Pulldown",
        "muscles": ["back"],
        "equipment": ["machines", "cables"],
        "type": "compound",
        "difficulty": ["beginner", "intermediate"],
        "base_weight_pct": 0.55,
        "vector": _vec(lose_weight=0.5, build_muscle=1, beginner=1, intermediate=1,
                       compound=1, back=1, machines=1, cables=1),
    },
    {
        "name": "Pull-Up",
        "muscles": ["back"],
        "equipment": ["bodyweight"],
        "type": "compound",
        "difficulty": ["intermediate", "advanced"],
        "base_weight_pct": 0.0,
        "vector": _vec(lose_weight=0.5, strength=0.7, build_muscle=1,
                       intermediate=1, advanced=1, compound=1, back=1, bodyweight=1),
    },
    {
        "name": "Cable Row",
        "muscles": ["back"],
        "equipment": ["cables"],
        "type": "compound",
        "difficulty": ["beginner", "intermediate"],
        "base_weight_pct": 0.45,
        "vector": _vec(build_muscle=1, beginner=1, intermediate=1,
                       compound=1, back=1, cables=1),
    },
    # ── LEGS ──────────────────────────────────────────────────────────────────
    {
        "name": "Barbell Squat",
        "muscles": ["legs"],
        "equipment": ["barbell"],
        "type": "compound",
        "difficulty": ["intermediate", "advanced"],
        "base_weight_pct": 0.85,
        "vector": _vec(strength=1, build_muscle=0.7, intermediate=1, advanced=1,
                       compound=1, legs=1, barbell=1),
    },
    {
        "name": "Leg Press",
        "muscles": ["legs"],
        "equipment": ["machines"],
        "type": "compound",
        "difficulty": ["beginner", "intermediate"],
        "base_weight_pct": 1.20,
        "vector": _vec(build_muscle=1, lose_weight=0.5, beginner=1, intermediate=1,
                       compound=1, legs=1, machines=1),
    },
    {
        "name": "Dumbbell Lunges",
        "muscles": ["legs"],
        "equipment": ["dumbbells"],
        "type": "compound",
        "difficulty": ["beginner", "intermediate"],
        "base_weight_pct": 0.20,
        "vector": _vec(lose_weight=1, build_muscle=0.7, beginner=1, intermediate=1,
                       compound=1, legs=1, dumbbells=1),
    },
    {
        "name": "Bodyweight Squat",
        "muscles": ["legs"],
        "equipment": ["bodyweight"],
        "type": "compound",
        "difficulty": ["beginner"],
        "base_weight_pct": 0.0,
        "vector": _vec(lose_weight=1, beginner=1, compound=1, legs=1, bodyweight=1),
    },
    {
        "name": "Leg Curl",
        "muscles": ["legs"],
        "equipment": ["machines"],
        "type": "isolation",
        "difficulty": ["beginner", "intermediate"],
        "base_weight_pct": 0.25,
        "vector": _vec(build_muscle=1, beginner=1, intermediate=1,
                       isolation=1, legs=1, machines=1),
    },
    {
        "name": "Romanian Deadlift",
        "muscles": ["legs"],
        "equipment": ["barbell", "dumbbells"],
        "type": "compound",
        "difficulty": ["intermediate"],
        "base_weight_pct": 0.60,
        "vector": _vec(build_muscle=1, strength=0.7, intermediate=1,
                       compound=1, legs=1, barbell=1, dumbbells=1),
    },
    # ── SHOULDERS ─────────────────────────────────────────────────────────────
    {
        "name": "Overhead Press",
        "muscles": ["shoulders"],
        "equipment": ["barbell"],
        "type": "compound",
        "difficulty": ["intermediate", "advanced"],
        "base_weight_pct": 0.55,
        "vector": _vec(strength=1, build_muscle=0.8, intermediate=1, advanced=1,
                       compound=1, shoulders=1, barbell=1),
    },
    {
        "name": "Dumbbell Shoulder Press",
        "muscles": ["shoulders"],
        "equipment": ["dumbbells"],
        "type": "compound",
        "difficulty": ["beginner", "intermediate"],
        "base_weight_pct": 0.20,
        "vector": _vec(build_muscle=1, lose_weight=0.3, beginner=1, intermediate=1,
                       compound=1, shoulders=1, dumbbells=1),
    },
    {
        "name": "Lateral Raise",
        "muscles": ["shoulders"],
        "equipment": ["dumbbells", "cables"],
        "type": "isolation",
        "difficulty": ["beginner", "intermediate"],
        "base_weight_pct": 0.07,
        "vector": _vec(lose_weight=0.3, build_muscle=1, beginner=1, intermediate=1,
                       isolation=1, shoulders=1, dumbbells=1, cables=1),
    },
    {
        "name": "Machine Shoulder Press",
        "muscles": ["shoulders"],
        "equipment": ["machines"],
        "type": "compound",
        "difficulty": ["beginner"],
        "base_weight_pct": 0.35,
        "vector": _vec(build_muscle=1, beginner=1, compound=1,
                       shoulders=1, machines=1),
    },
    # ── ARMS ──────────────────────────────────────────────────────────────────
    {
        "name": "Barbell Curl",
        "muscles": ["arms"],
        "equipment": ["barbell"],
        "type": "isolation",
        "difficulty": ["beginner", "intermediate"],
        "base_weight_pct": 0.25,
        "vector": _vec(build_muscle=1, beginner=1, intermediate=1,
                       isolation=1, arms=1, barbell=1),
    },
    {
        "name": "Dumbbell Curl",
        "muscles": ["arms"],
        "equipment": ["dumbbells"],
        "type": "isolation",
        "difficulty": ["beginner"],
        "base_weight_pct": 0.12,
        "vector": _vec(build_muscle=1, lose_weight=0.3, beginner=1,
                       isolation=1, arms=1, dumbbells=1),
    },
    {
        "name": "Tricep Pushdown",
        "muscles": ["arms"],
        "equipment": ["cables"],
        "type": "isolation",
        "difficulty": ["beginner", "intermediate"],
        "base_weight_pct": 0.18,
        "vector": _vec(build_muscle=1, lose_weight=0.3, beginner=1, intermediate=1,
                       isolation=1, arms=1, cables=1),
    },
    {
        "name": "Skull Crusher",
        "muscles": ["arms"],
        "equipment": ["barbell", "dumbbells"],
        "type": "isolation",
        "difficulty": ["intermediate"],
        "base_weight_pct": 0.20,
        "vector": _vec(build_muscle=1, intermediate=1, isolation=1,
                       arms=1, barbell=1, dumbbells=1),
    },
    {
        "name": "Dips",
        "muscles": ["arms", "chest"],
        "equipment": ["bodyweight"],
        "type": "compound",
        "difficulty": ["intermediate", "advanced"],
        "base_weight_pct": 0.0,
        "vector": _vec(strength=0.7, build_muscle=1, intermediate=1, advanced=1,
                       compound=1, arms=1, chest=1, bodyweight=1),
    },
    # ── CORE ──────────────────────────────────────────────────────────────────
    {
        "name": "Plank",
        "muscles": ["core"],
        "equipment": ["bodyweight"],
        "type": "isolation",
        "difficulty": ["beginner"],
        "base_weight_pct": 0.0,
        "vector": _vec(lose_weight=1, beginner=1, isolation=1, core=1, bodyweight=1),
    },
    {
        "name": "Cable Crunch",
        "muscles": ["core"],
        "equipment": ["cables"],
        "type": "isolation",
        "difficulty": ["beginner", "intermediate"],
        "base_weight_pct": 0.10,
        "vector": _vec(lose_weight=0.7, build_muscle=0.5, beginner=1, intermediate=1,
                       isolation=1, core=1, cables=1),
    },
    {
        "name": "Hanging Leg Raise",
        "muscles": ["core"],
        "equipment": ["bodyweight"],
        "type": "isolation",
        "difficulty": ["intermediate", "advanced"],
        "base_weight_pct": 0.0,
        "vector": _vec(lose_weight=1, build_muscle=0.3, intermediate=1, advanced=1,
                       isolation=1, core=1, bodyweight=1),
    },
    {
        "name": "Ab Wheel Rollout",
        "muscles": ["core"],
        "equipment": ["bodyweight"],
        "type": "isolation",
        "difficulty": ["intermediate", "advanced"],
        "base_weight_pct": 0.0,
        "vector": _vec(lose_weight=0.7, build_muscle=0.5, intermediate=1, advanced=1,
                       isolation=1, core=1, bodyweight=1),
    },
]
